### ISSUE TITLE
Field errors are printed in English

### ISSUE THREAD

**Issue by thomaslhostis** [adrianhurt/play-bootstrap3#17]
Hi,

In a multilingual application, it seems that error messages are always printed in English.

Is it just me?

**Comment by adrianhurt** [comment]
Hi @thomaslhostis,

I've checked it and it doesn't happen to me. Be sure that the implicit Lang object is present finally in the last template that calls the _b3_ helpers. Does it happen to you only for the helpers or also for other messages? For example, I've checked a simple form with a _required_ and _minLength_ constraints and call it like this:
```
@b3.text( form("name"), '_label -> Messages("name"), '_showConstraints -> true )
```
The label should be shown in your selected language (as it is called directly and not from the library), and the constraints should also be shown in that language if you have them within your messages file (for this example in _messages.es_)
```
constraint.required=Requerido
constraint.minLength=Longitud mínima: {0}
```

**Comment by adrianhurt** [comment]
Oops, no, forget that. You're right, the internal _Lang_ object is being missed. In my case it takes always the spanish one…

Ok, sorry for that. I think it happens only for infos (constraints) and errors. I'm now quite busy, but I'll try solve this issue in a couple of days.

Thanks for the issue!

**Comment by thomaslhostis** [comment]
No problem. Thank *you* for this very nice work. I really have to learn Scala because I would love to contribute. Meanwhile, if I have any suggestions, where should I put it?

**Comment by adrianhurt** [comment]
Hi again. I think it is already fixed. It was easier than I thought. If you have more suggestions you can open more issues or email me directly and we can discuss them. As you want. Every suggestion is always welcome! ;)

Thank you!
