### ISSUE TITLE
Do not render label in @b3.static when it is null

### ISSUE THREAD

**Issue by mkurz** [adrianhurt/play-bootstrap3#18]
E.g.

    @b3.static(null){
        something
    }

renders an empty `<label class="control-label col-md-X"></label>` instead of using the `col-md-offset-` approach.

**Comment by adrianhurt** [comment]
Hi,

Now you can do:

```
@b3.static("Label") { … }  // with a string label
@b3.static(Html("Label")) { … }  // with a html label
@b3.static() { … }  // if you want to omit the label
```

Thanks!!

**Comment by mkurz** [comment]
@adrianhurt Thanks!
