### ISSUE TITLE
Allow adding attributes to <option> elements of the @b3.select control

### ISSUE THREAD

**Issue by mkurz** [adrianhurt/play-bootstrap3#19]
I would like to add `data-*` attributes to each of the the `<option>...</option>` elements of the `@b3.select(...)` control.
But it seems it is not possible right now, because the `options` param has to be of type `Seq[(String,String)]` (for `value` and `label` only).

I want to have a result like:

    <select id="foo" name="foo" class="form-control">
        <option class="blank" value="">Select an option</option>
        <option value="A" data-calories="54">Apples</option>
        <option value="P" data-calories="58">Pears</option>
        <option value="B" data-calories="89">Bananas</option>
    </select>

**Comment by adrianhurt** [comment]
Hi @mkurz,

Your case is particular. I think the better option is to create your own select helper. You simply need to copy the file `b3/select.scala.html` into a new one within your views folder (ex: `app/views/b3/my/select.scala.html`) and modify the `options` param to something like `Seq[(String, String, Int)]` and add these values to the `<option>…</option>`. You have more information to create your own helpers in the documentation web.

**Comment by mkurz** [comment]
@adrianhurt Thanks, I created my own helper.

**Comment by mkurz** [comment]
Hi!
Just in case someone is interested and will read this:
Thanks to #39 you don't need to write your own custom helper anymore.
You can now write:
```html
@b3.select( fooForm("foo"), '_label -> "Options containing data attributes " ) { implicit values =>
  @b3.selectOption("opt_1", "Option 1", "data-something" -> "yeah")
}
```

**Comment by adrianhurt** [comment]
Exactly! :+1:
