### ISSUE TITLE
0.4 Release

### ISSUE THREAD

**Issue by philwills** [adrianhurt/play-bootstrap3#22]
Hello,

I was wondering if there are any issues preventing a non-snapshot 0.4 release? Happy to try and chip in if there are any blockers, but can't see anything on the issues list.

Apologies for opening this as an issue, but didn't know how else to get in touch.

Thanks for the library, it's been really handy.

Phil

**Comment by adrianhurt** [comment]
Thank you Phil. As you comment, there is no issues so I agree with you. It's the moment to release 0.4. In fact it's already released.
