### ISSUE TITLE
HashMap as select options

### ISSUE THREAD

**Issue by AlesJiranek** [adrianhurt/play-bootstrap3#27]
Is it possible to use hash map as select options?

**Comment by adrianhurt** [comment]
Hi @AlesJiranek. The only possibility is to use a `Seq[(String,String)]`, but you can use the `toSeq` function to convert a `Map[A,B]` to a `Seq[(A,B)]`.

**Comment by AlesJiranek** [comment]
Oh, great, thank you, sorry for dumb question

**Comment by adrianhurt** [comment]
Don't worry ;)
