### ISSUE TITLE
Constructor for global errors

### ISSUE THREAD

**Issue by bjfletcher** [adrianhurt/play-bootstrap3#28]
I'm wondering if people would be interested in having a constructor for global errors?  A Bootstrap-themed version of this (copied from Play documentation):

```scala
@if(userForm.hasGlobalErrors) {
    <ul>
    @userForm.globalErrors.foreach { error =>
        <li>error.message</li>
    }
    </ul>
}
```

**Comment by adrianhurt** [comment]
Hi @bjfletcher. Thanks for the proposal, but I think there is no standard way to do that. It depends on how you want to show your errors in your web. For example, I don't use any list but directly `alerts`
```
@form.globalErrors.map { error =>
  <div class="alert alert-danger" role="alert">@error.message</div>
}
```
Without the need for the first test for `hasGlobalErrors` method. In fact, I don't use directly this `alert`, but also a custom tag (like `@alert("error", msg)`). There are many ways to show your errors...

**Comment by bjfletcher** [comment]
@adrianhurt, actually that what you wrote there is exactly what I used. Perhaps worth putting this in the documentation and making sure it has "global" and "error" for those who Google?

**Comment by adrianhurt** [comment]
Sorry, but I don't think it is enough general to include it as a helper. And it is explained within the first page about [Handling form submission](https://www.playframework.com/documentation/2.3.x/ScalaForms#Displaying-errors-in-a-view-template) in the official Play documentation.

But you can create your own helper as it is explained in docs and use it like `@b3.showGlobalErrors(myForm)`.

In fact, if someday I have enough spare time, I would like to create a section in the web page with a list of custom helpers that anyone could upload and share...
