### ISSUE TITLE
Play 2.4.0 support

### ISSUE THREAD

**Issue by mkurz** [adrianhurt/play-bootstrap3#29]
Hi!

Play 2.4.0 RC2 was released already.
Could you please also release a snapshot or milestone with Play 2.4 support?

Thanks!

**Comment by adrianhurt** [comment]
Hi @mkurz, I've just released version 0.4.2 as it was, and 0.4.3-SNAPSHOT that for the moment it's built with new Play 2.3.9, jQuery 2.1.4 and Bootstrap 3.3.4.

During this week I will try to start another SNAPSHOT for Play 2.4.0

**Comment by adrianhurt** [comment]
It's done. I've split the project in two versions:
* 0.4.3-SNAPSHOT for Play 2.3.9
* 0.4.3-P24-SNAPSHOT for Play 2.4.0-RC2

You can see it in the documentation web page.

Please, try it to test it works (for the sample subproject is now working well)

**Comment by mkurz** [comment]
Thanks! I will upgrade a project to 2.4 this week hopefully, I will let you know if I run into some problems.

**Comment by adrianhurt** [comment]
Thanks

**Comment by rtyley** [comment]
Could you make a non-snapshot release of the Play 2.4 support? I'm using `0.4.4-P24-SNAPSHOT` right now, it works great and much appreciated! Here it is being used in [_submitGit_](https://submitgit.herokuapp.com/):

![image](https://cloud.githubusercontent.com/assets/52038/8261019/32b42366-16bf-11e5-9b47-5151e6547191.png)

**Comment by adrianhurt** [comment]
Hi @rtyley . Versions __0.4.4-P24__ and __0.4.4-P23__ are now released.

**Comment by rtyley** [comment]
Thanks @adrianhurt !
