### ISSUE TITLE
Using list / repeat in play-bootstrap3

### ISSUE THREAD

**Issue by MagnusAk78** [adrianhurt/play-bootstrap3#34]
"help wanted"

This is really just a question (not necessarily an issue) but I can't find a way to just send a message...

How do I use the list / repeat functions that "normal" play helpers support together with the b3 helpers?

btw. I really like the play-bootstrap3 project, thanks for sharing!

**Comment by MagnusAk78** [comment]
I realised that this is not relevant to solely play-bootstrap3 but a more general play issue.

**Comment by adrianhurt** [comment]
Hi @MagnusAk78. Yes, it is a general doubt about Play, not this plugin. It should works as it is explained at the Play docs, but using b3 helpers when needed.

```
@helper.repeat(myForm("emails"), min = 1) { emailField =>
    @b3.text(emailField, … )
}
```
