### ISSUE TITLE
'class -> "..." on controls overrides bootstrap classes

### ISSUE THREAD

**Issue by mkurz** [adrianhurt/play-bootstrap3#38]
E.g. when writing
```html
@b3.text(..., 'class -> "custom-class", ...)
@b3.select(..., 'class -> "custom-class", ...)
etc.
```
then **NO** `form-control` class is rendered.
As a fix I have to write 
```
@b3.text(..., 'class -> "form-control custom-class", ...)
```
I suggest @b3.* controls always should add the corresponding bootstrap `form-control` class, no matter if we define 'class -> "...".

Also see #25 which is similar (it was for `<form>` tags).

**Comment by adrianhurt** [comment]
Sorry for the delay. I'll try to have it tomorrow or during this weekend. Thanks

**Comment by adrianhurt** [comment]
Ok, it was easier than I thought. It's fixed for the last snapshot. Now I will have to start thinking about Bootstrap 4...
