### ISSUE TITLE
Please add support for optgroup

### ISSUE THREAD

**Issue by mkurz** [adrianhurt/play-bootstrap3#39]
See here:
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/optgroup

What do you think?

**Comment by adrianhurt** [comment]
I like it. But how could be the signature for that version `b3.select`? Something like this?

```
@(field: Field, options: Seq[(String, Seq[(String,String)])], args: (Symbol,Any)*)
```

It's hard to understand and fill in. Seeing that example of `optgroup` I've realized the library now doesn't allow to disable some of the options. So maybe we could create auxiliar helpers for `option` and `optgroup`. Like this:

```
@b3.select( fooForm("foo"), '_label -> "Simple select" ) { implicit values =>
  @b3.selectOption("opt_1" -> "Option 1")
  @b3.selectOption("opt_2" -> "Option 2", 'disabled -> true)
  @b3.selectOption("opt_3" -> "Option 3")
}

@b3.select( fooForm("foo"), '_label -> "Grouped select" ) { implicit values =>
  @b3.selectOptionGroup("Group 1") {
    @b3.selectOption("opt_1-1" -> "Option 1.1")
    @b3.selectOption("opt_1-2" -> "Option 1.2", 'disabled -> true)
    @b3.selectOption("opt_1-3" -> "Option 1.3")
  }
  @b3.selectOptionGroup("Group 2") { 
    ...
  }
}

@b3.select( fooForm("foo"), '_label -> "Fruits select" ) { implicit values =>
  @b3.selectOptionGroup("Citrus fruits") {
    @fruits.filter(_.isCitrus).map { citrus =>
      @b3.selectOption(citrus.id -> citrus.name)
    }
  }
  @b3.selectOptionGroup("Rest of fruits") {
    @fruits.filterNot(_.isCitrus).map { fruit =>
      @b3.selectOption(fruit.id -> fruit.name)
    }
  }
}
```

And the same for `b3.radio`…

What do you think?

I'll go on holiday, so I'll be disappeared for a couple of weeks. When I come back I'll try to do something with this.

**Comment by adrianhurt** [comment]
In fact, the 'b3.selectOptionGroup` would be unnecessary.

```
@b3.select( fooForm("foo"), '_label -> "Grouped select" ) { implicit values =>
  <optgroup label="Group 1">
    @b3.selectOption("opt_1-1" -> "Option 1.1")
    @b3.selectOption("opt_1-2" -> "Option 1.2", 'disabled -> true)
    @b3.selectOption("opt_1-3" -> "Option 1.3")
  </optgroup>
  <optgroup label="Group 2">
    ...
  </optgroup>
}
```

**Comment by adrianhurt** [comment]
It's now implemented within the last SNAPSHOT. You can check it at the docs page.

**Comment by mkurz** [comment]
@adrianhurt I am running into a **bug**:

I did not change my code at all, but after upgrading to the latest snapshot I am getting an exception:

```
Caused by: java.lang.IndexOutOfBoundsException: 0
	at scala.collection.mutable.ResizableArray$class.apply(ResizableArray.scala:43) ~[scala-library-2.11.7.jar:na]
	at scala.collection.mutable.ArrayBuffer.apply(ArrayBuffer.scala:48) ~[scala-library-2.11.7.jar:na]
	at views.html.b3.selectWithOptions_Scope0$selectWithOptions.apply(selectWithOptions.template.scala:26) ~[play-bootstrap3_2.11-0.4.5-P24-SNAPSHOT.jar:0.4.5-P24-SNAPSHOT]
	at views.html.b3.package$.select(package.scala:272) ~[play-bootstrap3_2.11-0.4.5-P24-SNAPSHOT.jar:0.4.5-P24-SNAPSHOT]
```

I think the problem is [here](https://github.com/adrianhurt/play-bootstrap3/blob/master/module/app/views/b3/selectWithOptions.scala.html#L2) and [here](https://github.com/adrianhurt/play-bootstrap3/blob/master/module/app/views/b3/radioWithOptions.scala.html#L2). I am pretty sure the code `'_default -> options(0)._1` causes the `IndexOutOfBoundsException`.
Why? Because I am using code like this:
```java
@b3.select(myForm("zipId"), options = ZIPDestination.findAllZip().map{ v => v.getId().toString() -> (v.getCity()) }, '_label -> Messages("core.pleaseChoosePlace"), '_default -> Messages("core.pleaseChoose"), '_required -> false)
```
In my code `ZIPDestination.findAllZip()` sometimes returns a list with ZERO length. So there is no `options(0)._1` with index 0 available. Also I am passing a `'_default` param which should be used already instead!

**Comment by adrianhurt** [comment]
Mmm, sorry for that. Give me a while...

**Comment by mkurz** [comment]
Thanks, it would be cool if you could fix that soon, because our build is broken right now because of this issue... (I know depending on a snapshot isn't a good thing to do...)

**Comment by adrianhurt** [comment]
I think it should be ok now. It could take a while to refresh the code from maven. Please, check it again and tell me if it's fixed. If not, reopen again the issue and tell me...

**Comment by mkurz** [comment]
Look like it is fixed. If I run into any other issue I will let you know.
Thanks!

**Comment by mkurz** [comment]
@adrianhurt I ran into another bug:
When adding `'_default -> "Select an option"` to the new `@b3.select(...) { ... }` it does not work.
Example from your documentation with the `_default` option:
```html
@b3.select( fooForm("foo"), '_label -> "Grouped select", '_default -> "Select an option" ) { implicit values =>
  <optgroup label="Group 1">
    @b3.selectOption("opt_1-1", "Option 1.1")
    @b3.selectOption("opt_1-2", "Option 1.2", 'disabled -> true)
    @b3.selectOption("opt_1-3", "Option 1.3")
  </optgroup>
  <optgroup label="Group 2">
    @b3.selectOption("opt_2-1", "Option 2.1", 'disabled -> true)
    @b3.selectOption("opt_2-2", "Option 2.2")
  </optgroup>
}
```
`"Select an option"` is not available - it *should* be the first item in the list!

**Comment by mkurz** [comment]
And one completely different thing:
Do you think it would make sense to add a very simple helper tag `@b3.optGroup`?
Example:
```html
@b3.select( fooForm("foo"), '_label -> "Grouped select", '_default -> "Select an option" ) { implicit values =>
  @b3.optGroup("Group 1") {
    @b3.selectOption("opt_1-1", "Option 1.1")
    @b3.selectOption("opt_1-2", "Option 1.2", 'disabled -> true)
    @b3.selectOption("opt_1-3", "Option 1.3")
  }
  @b3.optGroup("Group 2") {
    @b3.selectOption("opt_2-1", "Option 2.1", 'disabled -> true)
    @b3.selectOption("opt_2-2", "Option 2.2")
  }
}
```
What do you think? It would be a very "stupid" tag, just to avoid typos and also type less :smile:

**Comment by adrianhurt** [comment]
Mmm, definitively I have to correct this. However I'm not sure if it should work as you say (and I thought the first time) or if I should correct the docs to indicate that '_default doesn't really add the default option and it's only to give the ability to add a default input for readonly selects… It's a bit tricky, because the reason to implement this new version of `b3.select` is to give the ability to fully customize the code inside the select. And I think this should include the default option. You could need to customize the default. But then I realized that in case you have a readonly select you also need a default value for the hidden input. That's the reason of `_default` here. But I understand it's confusing… Now you can add your default option as:

```scala
@selectOption("defaultValue", "defaultName", 'class -> "blank")
```

I suppose the better option is to have a new `_readonlyValue` or something like that. But then I would probably drop `_default` from this select implementation.

And regarding the possibility of a `b3.optGroup`. I thought it at a first time, but I think it it doesn't add any relevant functionality and it's a particular case. I know it would avoid typos and it's shorter to write, but then for the same reason there would be loads of other cases for other HTML and Bootstrap codes. Obviously, I see for you it could be interesting and you can add your own helper easily, but I think it's more a regular "template tag" and not a "field constructor helper".

**Comment by mkurz** [comment]
@adrianhurt my thoughts:
I think we should keep the `'_default` for **all** sorts of `b3.select` (also the new one) - not just the readonly one.
Why?
For example in your docs you have
```
@fruits = @{ Seq("A"->"Apples","P"->"Pears","B"->"Bananas") }
@b3.select( fooForm("foo"), options = fruits, '_label -> "Select" )
```
How would you add a default now?
You would have to write
```
@fruits = @{ Seq(""->"Select an option", "A"->"Apples","P"->"Pears","B"->"Bananas") }
```
But I think this is not a very good approach. What if `fruits` come from the database or a Java enum? You do not store a value `Select an option` in the database. I think adding `'_default -> "Select an option"` is a very good solution.
In my opinion also for the new customizable `b3.select` it should be possible to write `'_default -> "Select an option"` and add is as the first value. So you don't have to care about adding the `class -> "blank"` as well. In case someone wants to customize the default he can still skip `'_default` and add his own `@selectOption("defaultValue"...)`. So everyone can choose! :smile: 

So I vote for keeping `'_default` and also make it work for the new `b3.select`. Please do not implement just `_readonlyValue`.
What do you think?

**Comment by adrianhurt** [comment]
Mmm, I see your point. However I'm not sure if I totally agree… For me, in the example the `fruits` value  would be usually taken from a database, enum or whatever that gets you a list of fruits. But what you are passing to `b3.select` is a list of option that an user can choose, and the first option is not a fruit. I suppose we could write:

```scala
@b3.select( fooForm("foo"), options = ("" -> "Select an option") +: fruits, '_label -> "Select your favorite fruit" )
```

In fact, I see another problem. There are two different cases for using a default value within a select: to use the default value as a valid one or to use it to indicate that you must select another one. And I think we aren't doing it well… For the first case (i.e. an "optional select") it would be better to change the text to something like that:

```scala
@b3.select( fooForm("foo"), options = ("" -> "I don't like fruits") +: fruits, '_label -> "Select your favorite fruit" )
```

And for the second case (i.e. a "required select") maybe we could use a `'_promptLabel` argument to add a __disabled__ default value:

```scala
@b3.select( fooForm("foo"), options = fruits, '_label -> "Select a fruit", '_promptLabel -> "Select one" )
```

However, as I said, I see a need for a default value specially for readonly selects. Up until now, you could pass a default value, but if not, the first option was taken (assuming that you should pass a default value if you have an empty option list). But with the new `b3.select` definition you can't take the first option, so you need the ability to pass a default one for readonly selects.

I think it's a conceptual problem. Maybe a good choice would be to keep the `'_default` as it is now in every `b3.select` as you say to keep the coherence we have had until now. But it's possible that I change it for the next version that I hope to start soon for bootstrap 4 (I have to think first how to rename the project to simply __play-bootstrap__). And maybe the there would be a unique `b4.select(...){ … }` definition.

**Comment by mkurz** [comment]
Hi!
What about naming the option `'_firstItem` or `'_firstOption` or `'_firstEntry` in the new version (for Bootstrap 4)? So a unique name no matter it is used for the "prompt label" or the "default" (the valid one) one?
However could you for now add the `_default` to all the `b3.select` versions please?

And yes, I think renaming the project to `play-bootstrap` would be a good idea when Bootstrap 4 comes out. So you don't loose the stars and the watchers on the project. You can then just maintain different branches for different versions of Bootstrap.

Thanks!

**Comment by adrianhurt** [comment]
Hi @mkurz. It's done

**Comment by mkurz** [comment]
@adrianhurt Thanks, it works!

What do you think about releasing a new stable version with all the latest changes?

**Comment by adrianhurt** [comment]
Yes, I'll do it. But I prefer to wait for a while to be sure there is no more bugs.

**Comment by mkurz** [comment]
Thanks!

**Comment by adrianhurt** [comment]
I finally released it. Sorry for the delay…

**Comment by mkurz** [comment]
@adrianhurt Thanks!

**Comment by florianschneider** [comment]
@adrianhurt I'm experiencing issues using the b3.select with _default and having one of the options pre-selected. Not sure if this is the right place to ask, though.

**Comment by adrianhurt** [comment]
Hi @florianschneider, please open a new issue and tell there what is exactly happening with your code. Add an example and explain what issue you are experiencing. I need more details to be able to help you… 😉
