### ISSUE TITLE
Plugin 0.4.5-P24 snapshot not found since Nov, 19

### ISSUE THREAD

**Issue by arisolucion** [adrianhurt/play-bootstrap3#42]
Building a Play 2.4 application with the 0.4.5-P24-SNAPSHOT started to fail since today. I've checked and it looks like the Jar is not available anymore at Sonatype repo:
https://oss.sonatype.org/content/repositories/snapshots/com/adrianhurt/play-bootstrap3_2.11/

Since today I started getting:

[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	::          UNRESOLVED DEPENDENCIES         ::
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	:: com.adrianhurt#play-bootstrap3_2.11;0.4.5-P24-SNAPSHOT: not found
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 
[warn] 	Note: Unresolved dependencies path:
[warn] 		com.adrianhurt:play-bootstrap3_2.11:0.4.5-P24-SNAPSHOT

Following the "Installation" instructions mentioned here:
http://play-bootstrap3.herokuapp.com/

And the example here:
https://github.com/adrianhurt/play-bootstrap3/blob/master/sample/build.sbt

My build.sbt contains:
resolvers += "Sonatype OSS Snapshots" at "https://oss.sonatype.org/content/repositories/snapshots/"
and
libraryDependencies ++= Seq(... , "com.adrianhurt" %% "play-bootstrap3" % "0.4.5-P24-SNAPSHOT")

Nothing changed in the code, it just started failing today.

**Comment by adrianhurt** [comment]
Hi, it seems that every SNAPSHOT is deleted automatically when it's final version is released. I didn't know… I suppose you had it in cache during these days. Anyway, you can simply use the version __0.4.5-P24__, without the "-SNAPSHOT". It's exactly the same code as before.

**Comment by arisolucion** [comment]
Hi! thank you very much for this plugin and the quick reply. Just to let you know that your suggestion worked. I've removed the -SNAPSHOT and now it compiles correctly again.
Thanks again!!!

**Comment by adrianhurt** [comment]
You're welcome!
